## configs used for default model + loss construction

mean_net:
  model_class: 'FCResNet'
  hidden_dim: 512
  architect: 'concat'
  dropout_rate: 0.1
  activation: 'relu'
  use_softplus: False
  clip: False
  loss_type: 'MSE'
  is_modeling_inverse: False
  
mse_variance_net:
  model_class: 'FCResNet'
  n_degree: 2
  hidden_dim: 512
  architect: 'concat'
  dropout_rate: 0.1
  activation: 'elu'
  use_softplus: True
  clip: True
  loss_type: 'MSE'
  is_modeling_inverse: False

nll_variance_net:
  model_class: 'FCResNet'
  n_degree: 2
  hidden_dim: 512
  architect: 'concat'
  dropout_rate: 0.1
  activation: 'elu'
  use_softplus: True
  clip: False
  loss_type: 'NLL'
  is_modeling_inverse: True

