mean_net:
  learning_rate: 0.0008
  weight_decay: 0.0001
  reduce_LR_mode: 'min'
  reduce_LR_factor: 0.9
  reduce_LR_patience: 5
  early_stop_patience: 30
  batch_size: 64
  max_epochs: 200
  
mse_variance_net:
  learning_rate: 0.0008
  weight_decay: 0.0001
  reduce_LR_mode: 'min'
  reduce_LR_factor: 0.9
  reduce_LR_patience: 5
  early_stop_patience: 30
  batch_size: 64
  max_epochs: 200
  
nll_variance_net:
  learning_rate: 0.0008
  weight_decay: 0.0001
  reduce_LR_mode: 'min'
  reduce_LR_factor: 0.9
  reduce_LR_patience: 5
  early_stop_patience: 30
  batch_size: 64
  max_epochs: 200
